name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./backend

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./backend

    - name: Publish
      run: dotnet publish -c Release -o publish
      working-directory: ./backend

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-artifact
        path: backend/publish/